# SPDX-License-Identifier: MIT
---

- name: Create {{ item.name }}.spec
  template:
    dest: "/home/{{ pkmaint_mockuser | default(__pkmaint_mockuser, true)
      }}/rpmbuild/SPECS/{{ item.name }}.spec"
    src: "{{ item.name }}.spec.j2"
    group: "{{ pkmaint_mockuser | default(__pkmaint_mockuser, true) }}"
    owner: "{{ pkmaint_mockuser | default(__pkmaint_mockuser, true) }}"
    force: yes

- name: Get {{ item.name }}'s sources
  include_tasks: get_sources.yml
  loop: "{{ item.sources }}"
  loop_control:
    loop_var: source_item

- name: Get {{ item.name }}'s patches
  include_tasks: get_patches.yml
  loop: "{{ item.patches }}"
  loop_control:
    loop_var: patch_item
