# SPDX-License-Identifier: MIT
---

- name: Copy the patch from host
  copy:
    src: "{{ patch_item }}"
    dest: "/home/{{ pkmaint_mockuser | default(__pkmaint_mockuser, true)
      }}/rpmbuild/SOURCES/{{ patch_item }}"
    group: "{{ pkmaint_mockuser | default(__pkmaint_mockuser, true) }}"
    owner: "{{ pkmaint_mockuser | default(__pkmaint_mockuser, true) }}"
    force: yes
