# SPDX-License-Identifier: MIT
---

- name: Initialize repository from data
  yum_repository:
    name: "{{ item.name }}"
    description: "{{ item.description | default(item.name) }}"
    baseurl: "{{ item.baseurl }}"
    gpgcheck: "{{ item.gpgcheck | default(false) }}"
    enabled: "{{ item.enabled | default(true) }}"
    state: present
  when:
    - 'name' in item

- name: Initialize repository from package
  package:
    name: "{{ item.package }}"
    state: present
  when:
    - 'package' in item
