# SPDX-License-Identifier: MIT
---

- name: Set facts
  set_fact:
    __pkmaint_envvar_imagevarsfile_fact: "{{
      pkmaint_envvar_imagevarsfile
      | default(__pkmaint_envvar_imagevarsfile, true)
    }}"
    __pkmaint_mockuser_fact: "{{
      pkmaint_mockuser
      | default(__pkmaint_mockuser, true)
    }}"
    __pkmaint_localrepo_fact: "{{
      pkmaint_localrepo
      | default(__pkmaint_localrepo, true)
    }}"
    __pkmaint_buildscript_fact: "{{
      pkmaint_buildscript
      | default(__pkmaint_buildscript, true)
    }}"
    __pkmaint_updatelocalreposcript_fact: "{{
      pkmaint_updatelocalreposcript
      | default(__pkmaint_updatelocalreposcript, true)
    }}"

- name: Include VM image specific variables
  include_vars: "{{ lookup('env', __pkmaint_envvar_imagevarsfile_fact) }}"
  when:
    - lookup(
        'env', __pkmaint_envvar_imagevarsfile_fact, errors='ignore'
      ) | length > 0
    - lookup(
        'file', lookup('env', __pkmaint_envvar_imagevarsfile_fact),
        errors='ignore'
      ) | length > 0

- name: Initialize base repositories
  include_tasks: init_repos.yml
  loop: "{{ pkmaint_baserepos }}"

- name: Install base packages
  package:
    name: "{{ pkmaint_basepackages }}"
    state: present
  when:
    - pkmaint_basepackages | length > 0

- name: Initialize custom repositories
  include_tasks: init_repos.yml
  loop: "{{ pkmaint_customrepos }}"

- name: Install custom packages
  package:
    name: "{{ __pkmaint_packages | union(pkmaint_custompackages) }}"
    state: present
  when:
    - __pkmaint_packages | union(pkmaint_custompackages) | length > 0

- name: Create mock profiles
  template:
    dest: /etc/mock/{{ item.name }}.cfg
    src: "{{ __pkmaint_mockprofile }}.j2"
    force: yes
    backup: yes
  loop: "{{ pkmaint_mock_profiles }}"

- name: Create user accounts
  include_tasks: create_users.yml
  loop: "{{
    [ {
      'name': __pkmaint_mockuser_fact,
      'groups': [ 'wheel', 'mock' ],
      'append': true
    } ] + pkmaint_users
  }}"

- name: Build rpmbuild tree for {{ __pkmaint_mockuser_fact }}
  file:
    path: "/home/{{ __pkmaint_mockuser_fact }}/{{ item }}"
    group: "{{ __pkmaint_mockuser_fact }}"
    owner: "{{ __pkmaint_mockuser_fact }}"
    state: directory
  loop:
    - "rpmbuild/BUILD"
    - "rpmbuild/BUILDROOT"
    - "rpmbuild/RPMS"
    - "rpmbuild/SOURCES"
    - "rpmbuild/SPECS"
    - "rpmbuild/SRPMS"

- name: Get subjects
  include_tasks: get_subjects.yml
  loop: "{{ pkmaint_subjects }}"

- name: Create a build script
  template:
    dest: "/home/{{ __pkmaint_mockuser_fact }}/{{ __pkmaint_buildscript_fact
      }}"
    src: "{{ __pkmaint_buildscript }}.j2"
    mode: 0755
    group: "{{ __pkmaint_mockuser_fact }}"
    owner: "{{ __pkmaint_mockuser_fact }}"
    force: yes

- name: Create local yum based repository tree
  file:
    path: "{{ __pkmaint_localreporoot }}/{{ pkmaint_distro }}/{{
      pkmaint_releasever }}/{{ __pkmaint_localrepo_fact }}/{{
      pkmaint_basearch }}/{{ __pkmaint_pkgsdirname }}"
    mode: o-w+r
    group: root
    owner: root
    state: directory

- name: Create local yum based repository
  yum_repository:
    name: "{{ __pkmaint_localrepo_fact }}"
    description: Local repository
    baseurl: "file://{{ __pkmaint_localreporoot }}/{{ pkmaint_distro }}/{{
      pkmaint_releasever }}/{{ __pkmaint_localrepo_fact }}/{{
      pkmaint_basearch }}"
    enabled: no
    gpgcheck: no
    priority: 1
    protect: yes
    state: present
    file: "/etc/yum.repos.d/{{ __pkmaint_localrepo_fact }}.repo"

- name: Create an update local repo script
  template:
    dest: "/usr/local/bin/{{ __pkmaint_updatelocalreposcript_fact }}"
    src: "{{ __pkmaint_updatelocalreposcript }}.j2"
    mode: 0755
    force: yes
