# SPDX-License-Identifier: MIT
---

- name: Enable passwordless sudo
  lineinfile:
    dest: /etc/sudoers
    regexp: "^%wheel"
    line: "%wheel	ALL=(ALL)	NOPASSWD: ALL"
    state: present
    validate: "visudo -cf %s"
