# SPDX-License-Identifier: MIT
---

- name: Install mock and base packages
  package:
    name: "{{ __pkmaint_packages.base + __pkmaint_packages.mock }}"
    state: present

- name: Create mock user account
  include_tasks: create_user.yml
  loop: "{{ [ {
    'name': ( pkmaint_mockuser | default(__pkmaint_mockuser, true) ),
    'groups': [ 'wheel', 'mock' ],
    'append': true } ] }}"

- name: Create mock profiles
  template:
    dest: /etc/mock/{{ item.name }}.cfg
    src: "{{ item.template | default((
      pkmaint_mockprofile_template | default(
        __pkmaint_mockprofile_template, true
      )), true) }}.j2"
    force: yes
    backup: yes
  loop: "{{ pkmaint_mock_profiles }}"

- name: Build rpmbuild tree for {{
    pkmaint_mockuser | default(__pkmaint_mockuser, true) }}
  file:
    path: "/home/{{ pkmaint_mockuser | default(__pkmaint_mockuser, true)
      }}/rpmbuild/{{ item }}"
    group: "{{ pkmaint_mockuser | default(__pkmaint_mockuser, true) }}"
    owner: "{{ pkmaint_mockuser | default(__pkmaint_mockuser, true) }}"
    state: directory
  loop:
    - BUILD
    - BUILDROOT
    - RPMS
    - SOURCES
    - SPECS
    - SRPMS
